# Generated by Django 2.0 on 2018-02-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180211_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catlist',
            new_name='name',
        ),
    ]
