# Generated by Django 2.0 on 2018-02-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180213_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(default='http://weclipart.com/google+images+sun+clipart'),
            preserve_default=False,
        ),
    ]
