# Generated by Django 2.0 on 2018-02-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180216_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('a', 'Action'), ('b', 'Arcade'), ('c', 'Indie'), ('d', 'Puzzle'), ('e', 'Strategy')], default='a', max_length=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
