# Generated by Django 2.0 on 2018-02-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180217_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
