# Generated by Django 2.0 on 2018-02-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180216_1925'),
        ('website', '0006_auto_20180217_2155'),
    ]

    operations = [
    ]
