# Generated by Django 2.0 on 2018-02-03 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restsession',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='restsession',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 10, 14, 59, 477379, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='restsession',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 10, 14, 59, 477438, tzinfo=utc)),
        ),
    ]
