# Generated by Django 2.0 on 2018-02-03 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20180203_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restsession',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='restsession',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='restsession',
            name='token',
            field=models.CharField(default='fqc1D8P9hDg1Ha4fBKxVrMJbyZctySkG', editable=False, max_length=32),
        ),
    ]
