# Generated by Django 2.0 on 2018-02-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20180203_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='token',
            field=models.CharField(default='XvkWOOqkZwMmb0MicCbTBnTqY492CLeY', editable=False, max_length=32),
        ),
    ]
