# Generated by Django 2.0 on 2018-02-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20180204_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='token',
            field=models.CharField(default='VaXSKTwRYjgGpfgYaoMsAUBeJdscC4dT', editable=False, max_length=32),
        ),
    ]
