# Generated by Django 2.0 on 2018-02-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_auto_20180204_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='token',
            field=models.CharField(default='D4GG6SlCQ8fivJObhqIcN4tmBUkRhib2', editable=False, max_length=32),
        ),
    ]
