# Generated by Django 2.0 on 2018-02-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20180203_1935'),
        ('rest', '0008_auto_20180204_0017'),
    ]

    operations = [
    ]
