# Generated by Django 2.0 on 2018-02-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20180211_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='token',
            field=models.CharField(default='Y26jcVmB7zR4UKQajPAsCVcYUqtjSdKj', editable=False, max_length=32),
        ),
    ]
