# Generated by Django 2.0 on 2018-02-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20180211_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='token',
            field=models.CharField(default='myx4O4i2QsF9KdVVErixKz5lIcFFTvsq', editable=False, max_length=32),
        ),
    ]
