# Generated by Django 2.0 on 2018-02-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20180206_2011'),
        ('rest', '0010_auto_20180212_1711'),
    ]

    operations = [
    ]
