# Generated by Django 2.0 on 2018-02-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_merge_20180213_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='token',
            field=models.CharField(default='J7I7QyMJKn7Buk8e2YZumgRLIUDfl7he', editable=False, max_length=32),
        ),
    ]
