# Generated by Django 2.0 on 2018-02-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_auto_20180217_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='token',
            field=models.CharField(default='jtpvBvB2fsR1M2cA9Fi61BfIMkzq0aZC', editable=False, max_length=32),
        ),
    ]
