# Generated by Django 2.0 on 2018-02-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_auto_20180217_2158'),
        ('rest', '0012_auto_20180211_1526'),
    ]

    operations = [
    ]
